[.lead]
In this module we study the effect of various flags and implementation options on startup time for the function invoker.

You can run the benchmarks by cloning this repository next to your clone of `sk8s` (and using the default directory names). If you want to change the locations or names of directories look at the `MainBenchmark` where it creates its state, and change the path to the `java-function-invoker` module. The version label for teh jar is also hard coded.

== Results

=== Baseline

Results in seconds (baseline commit `d53434b`, 0.0.1-SNAPSHOT) on hardware "X1 Carbon" Thinkpad (4-core Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
):

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  5.522 ± 0.330   s/op
MainBenchmark.main      norm    ss   10  3.685 ± 0.095   s/op
MainBenchmark.main      expl    ss   10  5.807 ± 0.409   s/op
MainBenchmark.main      fast    ss   10  3.834 ± 0.122   s/op
MainBenchmark.main      main    ss   10  4.044 ± 0.203   s/op
MainBenchmark.main      best    ss   10  2.251 ± 0.108   s/op
```
<1> (base) Fat jar no JVM options (i.e. roughly where we were before any optimizations)
<2> (norm) Fat jar with extended JVM options
<3> (expl) Exploded jar with no JVM options, main class `JarLauncher`
<4> (fast) Exploded jar with extended JVM options, main class `JarLauncher`
<5> (main) Exploded jar with no JVM options, main class from app
<6> (best) Exploded jar with extended JVM options, main class from app

On better hardware "Desktop" (8-core Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz):

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  2.889 ± 0.130   s/op
MainBenchmark.main      norm    ss   10  2.727 ± 0.034   s/op
MainBenchmark.main      expl    ss   10  2.907 ± 0.166   s/op
MainBenchmark.main      fast    ss   10  2.808 ± 0.050   s/op
MainBenchmark.main      main    ss   10  2.129 ± 0.082   s/op
MainBenchmark.main      best    ss   10  1.559 ± 0.040   s/op
```

The rest of the data below uses the "X1 Carbon".


=== With Flux Support

Supported but not enabled, so same tests:

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  5.451 ± 0.397   s/op
MainBenchmark.main      norm    ss   10  3.801 ± 0.183   s/op
MainBenchmark.main      expl    ss   10  5.896 ± 0.430   s/op
MainBenchmark.main      fast    ss   10  4.019 ± 0.858   s/op
MainBenchmark.main      main    ss   10  4.109 ± 0.163   s/op
MainBenchmark.main      best    ss   10  2.344 ± 0.136   s/op
```

(No regression.)

With a `FluxDoubler` and an isolated classpath:

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  7.275 ± 0.516   s/op
MainBenchmark.main      norm    ss   10  5.415 ± 0.061   s/op
MainBenchmark.main      expl    ss   10  7.871 ± 0.483   s/op
MainBenchmark.main      fast    ss   10  5.523 ± 0.124   s/op
MainBenchmark.main      main    ss   10  4.102 ± 0.201   s/op
MainBenchmark.main      best    ss   10  2.315 ± 0.089   s/op
```

Fat jar slower (don't know why). Exploded not that different, maybe even a bit faster.

=== Load Function from Jar

Instead of loading the function from `test-classes` in the `java-function-invoker` would could load from a jar, e.g. the `function-sample-pof` in `spring-cloud-function`.

Baseline (load from a jar, but not use isolated class loader):

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  5.479 ± 0.357   s/op
MainBenchmark.main      norm    ss   10  3.702 ± 0.048   s/op
MainBenchmark.main      expl    ss   10  5.847 ± 0.214   s/op
MainBenchmark.main      fast    ss   10  3.803 ± 0.089   s/op
MainBenchmark.main      main    ss   10  3.978 ± 0.276   s/op
MainBenchmark.main      best    ss   10  2.253 ± 0.082   s/op
```

Isolated class loader with function of `Flux`:

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  7.406 ± 0.384   s/op
MainBenchmark.main      norm    ss   10  5.438 ± 0.137   s/op
MainBenchmark.main      expl    ss   10  8.026 ± 0.532   s/op
MainBenchmark.main      fast    ss   10  5.614 ± 0.137   s/op
MainBenchmark.main      main    ss   10  4.135 ± 0.353   s/op
MainBenchmark.main      best    ss   10  2.376 ± 0.105   s/op
```

=== Remove the Actuator

The Actuator is pulled in via the Prometheus starter (3rd party). Removing that should speed things up. Results, relative to baseline:

```
Benchmark           (sample)  Mode  Cnt  Score   Error  Units
MainBenchmark.main      base    ss   10  4.260 ± 0.294   s/op
MainBenchmark.main      norm    ss   10  2.693 ± 0.066   s/op
MainBenchmark.main      expl    ss   10  4.725 ± 0.385   s/op
MainBenchmark.main      fast    ss   10  2.813 ± 0.104   s/op
MainBenchmark.main      main    ss   10  3.115 ± 0.171   s/op
MainBenchmark.main      best    ss   10  1.774 ± 0.074   s/op
```